name: SignCarousel
version: '${project.version}'
main: com.ashkiano.signcarousel.SignCarousel
api-version: '1.20'
authors: [AshKiano]
description: Changes sign text by defined list in config and time also defined in config.
website: https://www.ashkiano.com